spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cxwinnie/springcloud-test.git
server:
  port: 8080
########  http://127.0.0.1:8080/application-default/master,http://127.0.0.1:8080/application-default.yml,http://127.0.0.1:8080/application-dev.yml