spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cxwinnie/springcloud-test-config.git
          username:
          password:
server:
  port: 8080
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123