server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-gateway-zuul
zuul:
  routes:
    users:
      path: /users/**
      serviceId: microservice-provider-user

ribbon:
  eureka:
    enabled: false

microservice-provider-user:             #这边是serviceId
  ribbon:
    listOfServers: http://127.0.0.1:7900/,http://127.0.0.1:7901/