spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cxwinnie/springcloud-test-config.git
          username:
          password:
  application:
    name: microservice-config-server-eureka
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true